version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shivanadapg@7422
      MYSQL_DATABASE: "AkashSG$Rental"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: .
    container_name: flask_backend
    restart: always
    env_file:
      - .env
    environment:
      PRIMARY_DB_HOST: db
      PRIMARY_DB_DATABASE: AkashSG$Rental
      PRIMARY_DB_USER: root
      PRIMARY_DB_PASSWORD: Shivanadapg@7422
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  db_data:
